Name:           ros-indigo-cob-vision-utils
Version:        0.6.9
Release:        0%{?dist}
Summary:        ROS cob_vision_utils package

Group:          Development/Libraries
License:        LGPL
URL:            http://wiki.ros.org/cob_vision_utils
Source0:        %{name}-%{version}.tar.gz

Requires:       opencv-devel
Requires:       ros-indigo-cmake-modules
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-visualization-msgs
Requires:       tinyxml-devel
BuildRequires:  opencv-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cmake-modules
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-visualization-msgs
BuildRequires:  tinyxml-devel

%description
Contains utilities used within the object detection tool chain.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Jul 18 2017 Richard Bormann <rmb@ipa.fhg.de> - 0.6.9-0
- Autogenerated by Bloom

* Mon Oct 10 2016 Richard Bormann <rmb@ipa.fhg.de> - 0.6.8-0
- Autogenerated by Bloom

* Fri Apr 01 2016 Richard Bormann <rmb@ipa.fhg.de> - 0.6.7-0
- Autogenerated by Bloom

* Wed Jun 17 2015 Jan Fischer <jsf@ipa.fhg.de> - 0.6.6-0
- Autogenerated by Bloom

* Wed Jun 17 2015 Jan Fischer <jsf@ipa.fhg.de> - 0.6.5-0
- Autogenerated by Bloom

* Wed Sep 17 2014 Jan Fischer <jsf@ipa.fhg.de> - 0.6.4-0
- Autogenerated by Bloom

* Mon Sep 08 2014 Jan Fischer <jsf@ipa.fhg.de> - 0.6.3-0
- Autogenerated by Bloom

* Mon Sep 01 2014 Jan Fischer <jsf@ipa.fhg.de> - 0.6.2-0
- Autogenerated by Bloom

* Fri Aug 29 2014 Jan Fischer <jsf@ipa.fhg.de> - 0.6.1-2
- Autogenerated by Bloom

* Fri Aug 29 2014 Jan Fischer <jsf@ipa.fhg.de> - 0.6.1-1
- Autogenerated by Bloom

* Thu Aug 28 2014 Jan Fischer <jsf@ipa.fhg.de> - 0.6.1-0
- Autogenerated by Bloom

* Tue Aug 26 2014 Jan Fischer <jsf@ipa.fhg.de> - 0.5.5-0
- Autogenerated by Bloom

